export const LOAD_ALL_CLASSES_SUCCESS = "LOAD_ALL_CLASSES_SUCCESS";
export const LOAD_CLASS_SUCCESS = "LOAD_CLASS_SUCCESS";
export const ADD_CLASS_SUCCESS = "ADD_CLASS_SUCCESS";
export const SELECT_CLASS = "SELECT_CLASS";