export const UPDATE_BOOKING_DETAILS = "UPDATE_BOOKING_DETAILS";
export const GET_CLASS_DATA_FAILED = "GET_CLASS_DATA_FAILED";
export const GET_ClASS_DATA_SUCCESS = "GET_CLASS_DATA_SUCCESS";
export const SUBMIT_BOOKING_FAILED = "SUBMIT_BOOKING_FAILED";
export const SUBMIT_BOOKING_SUCCESS = "SUBMIT_BOOKING_SUCCESS";
export const SELECT_CLASS_FOR_BOOKING = "SELECT_CLASS_FOR_BOOKING";