export const UPDATE_ALL_COSTS = "UPDATE_ALL_COSTS";
export const UPDATE_BOOKER_AND_BOOKING_DETAILS = "UPDATE_BOOKER_AND_BOOKING_DETAILS";
export const RESET = "RESET";
export const UPDATE_CLASS_ID = "UPDATE_CLASS_ID";
export const SET_BOOKING_ERRORS = "SET_BOOKING_ERRORS";
export const SET_BOOKING_SUBMIT_IS_LOADING = "SET_BOOKING_SUBMIT_IS_LOADING";