export const UPDATE_MEAL_KITS_BOOKED = "UPDATE_MEAL_KITS_BOOKED";
export const UPDATE_ALL_COSTS = "UPDATE_ALL_COSTS";
export const UPDATE_GENERAL_BOOKER_AND_BOOKING_DETAILS = "UPDATE_GENERAL_BOOKER_AND_BOOKING_DETAILS"