export const LOAD_BOOKING_DETAILS_FAILED = "LOAD_BOOKING_DETAILS_FAILED";
export const LOAD_BOOKING_DETAILS_SUCCESS = "LOAD_BOOKING_DETAILS_SUCCESS";
export const CHECKOUT_FAILED = "CHECKOUT_FAILED";
export const CHECKOUT_SUCCESS = "CHECKOUT_SUCCESS";