export const SET_BOOKING_DETAILS = 'SET_BOOKING_DETAILS';
export const SET_LOAD_BOOKING_DETAILS_ERROR = 'SET_LOAD_BOOKING_DETAILS_ERROR';
export const SET_CHECKOUT_ERRORS = 'SET_CHECKOUT_ERRORS';
export const SET_CHECKOUT_LOADING = 'SET_CHECKOUT_LOADING';
export const SET_RECAPTCHA_ERROR = 'SET_RECAPTCHA_ERROR';