export const LOAD_POSTS_FAILED = "LOAD_POSTS_FAILED";
export const LOAD_POSTS_SUCCESS = "LOAD_POSTS_SUCCESS";
export const LOAD_POSTS = "LOAD_POSTS";
export const SELECT_BLOG_POST = "SElECT_BLOG_POST";
export const LOAD_POST_SUCCESS = "LOAD_POST_SUCCESS";
export const LOAD_POST_FAILED = "LOAD_POST_FAILED";