export const FAILED_TO_VERIFY_BOOKING_SUCCESS = "FAILED_TO_VERIFY_BOOKING_SUCCESS";
export const BOOKING_SUCCESS_VERIFIED = "BOOKING_SUCCESS_VERIFIED";
export const SEND_CONFIRMATIONS_FAILED = "SEND_CONFIRMATIONS_FAILED";
export const SEND_CONFIRMATIONS_SUCCESS = "SEND_CONFIRMATIONS_SUCCESS";